DROP TABLE IF EXISTS DATI_STAGIONE;
DROP TABLE IF EXISTS DATI_AREA_AFFARI;
DROP TABLE IF EXISTS DATI_FATTURATO;
DROP TABLE IF EXISTS DATI_PRODUZIONE;
DROP TABLE IF EXISTS DATI_RILEVAZIONE_TERRENO;
DROP TABLE IF EXISTS DATI_AMBIENTE;
DROP TABLE IF EXISTS DATI_COLTURA;
DROP TABLE IF EXISTS DATI_PARTICELLA;
DROP TABLE IF EXISTS DATI_ECONOMICI_NAZIONALI;
DROP TABLE IF EXISTS DATI_ORTAGGIO;
DROP TABLE IF EXISTS DATI_LITOLOGIA;
DROP TABLE IF EXISTS DATI_FAMIGLIA;
DROP TABLE IF EXISTS DATI_RANGE_STAGIONE_SEMINA;
DROP TABLE IF EXISTS DATI_AZIENDA;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;

DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ;

-- Tabella dati stagione
CREATE TABLE DATI_STAGIONE (
	NOME VARCHAR(255) NOT NULL PRIMARY KEY,
	MESE_GIORNO_INIZIO VARCHAR(255),
	MESE_GIORNO_FINE VARCHAR(255),
	RANGE_TEMPERATURA VARCHAR(255),
	RANGE_UMIDITA VARCHAR(255),
	RANGE_PRECIPITAZIONI VARCHAR(255),
	RANGE_IRRAGGIAMENTO VARCHAR(255),
	RANGE_OMBREGGIAMENTO VARCHAR(255)
);

--Tabella dati range stagione semina
CREATE TABLE DATI_RANGE_STAGIONE_SEMINA (
	ID_RANGE_STAGIONE_SEMINA BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MESE_SEMINA_MIN VARCHAR(255),
	MESE_SEMINA_MAX VARCHAR(255),
	STAGIONE VARCHAR(255)
);

-- Tabella dati azienda
CREATE TABLE DATI_AZIENDA (
	ID_AZIENDA BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RAGIONE_SOCIALE VARCHAR(255),
	ANNO_FONDAZIONE VARCHAR(255),
	TIPOLOGIA VARCHAR(255),
	ATECO VARCHAR(255),
	NUM_DIPENDENTI BIGINT
);

-- Tabella dati famiglia
CREATE TABLE DATI_FAMIGLIA (
	ID_FAMIGLIA BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIPOLOGIA VARCHAR(255),
	DESCRIZIONE VARCHAR(255)
);

-- Tabella dati ortaggio
CREATE TABLE DATI_ORTAGGIO (
	ID_ORTAGGIO BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255),
	DESCRIZIONE VARCHAR(255),
	GIORNI_SEMINA INT,
    GIORNI_GERMINAZIONE INT,
    GIORNI_TRAPIANTO INT,
    GIORNI_MATURAZIONE INT,
    GIORNI_RACCOLTA INT,
	PESO_MEDIO DECIMAL(5,2),
	VOLUME_MQ DECIMAL(5,2),
	ID_FAMIGLIA BIGINT,
	ID_RANGE_STAGIONE_SEMINA BIGINT,
	FOREIGN KEY (ID_FAMIGLIA) REFERENCES DATI_FAMIGLIA(ID_FAMIGLIA),
	FOREIGN KEY (ID_RANGE_STAGIONE_SEMINA) REFERENCES DATI_RANGE_STAGIONE_SEMINA(ID_RANGE_STAGIONE_SEMINA)
);

-- Tabella dati economici nazionali
CREATE TABLE DATI_ECONOMICI_NAZIONALI (
	ID_ECONOMIA BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ANNO_RIFERIMENTO VARCHAR(255),
	PRODUZIONE_MEDIA DECIMAL(10,2),
	PREZZO_VENDITA_MEDIO DECIMAL(5,2),
	ID_ORTAGGIO BIGINT,
	FOREIGN KEY (ID_ORTAGGIO) REFERENCES DATI_ORTAGGIO(ID_ORTAGGIO)
);

-- Tabella dati area affari
CREATE TABLE DATI_AREA_AFFARI (
	ID_AREA_AFFARI BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ANAGRAFICA VARCHAR(255),
	CANALE_VENDITA VARCHAR(255),
	ACCESSIBILITA VARCHAR(255),
	ID_ORTAGGIO BIGINT,
	FOREIGN KEY (ID_ORTAGGIO) REFERENCES DATI_ORTAGGIO(ID_ORTAGGIO)
);

-- Tabella dati litologia
CREATE TABLE DATI_LITOLOGIA (
	ID_LITOLOGIA BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIPOLOGIA VARCHAR(255),
	DESCRIZIONE VARCHAR(255)
);

-- Tabella dati particella
CREATE TABLE DATI_PARTICELLA (
    ID_PARTICELLA BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	COMUNE VARCHAR(255),
	FOGLIO VARCHAR(255),
	QUALITA VARCHAR(255),
	ANNO_INSTALLAZIONE VARCHAR(255),
	COSTO DECIMAL(6,2),
    ESTENSIONE DECIMAL(6,2),
    PENDENZA DECIMAL(5,2),
    ESPOSIZIONE VARCHAR(255),
    ID_LITOLOGIA BIGINT,
	FOREIGN KEY (ID_LITOLOGIA) REFERENCES DATI_LITOLOGIA(ID_LITOLOGIA)
);

-- Tabella dati fatturato
CREATE TABLE DATI_FATTURATO (
	ID_FATTURATO BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ANNO_RIFERIMENTO VARCHAR(255),
	RICAVI_VENDITA DECIMAL(10,2),
	SPESE_GENERALI DECIMAL(10,2),
	INTERESSI_ATTIVI DECIMAL(10,2),
	INTERESSI_PASSIVI DECIMAL(10,2),
	ID_PARTICELLA BIGINT,
	FOREIGN KEY (ID_PARTICELLA) REFERENCES DATI_PARTICELLA(ID_PARTICELLA)
);

-- Tabella dati coltura
CREATE TABLE DATI_COLTURA (
    ID_COLTURA BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PREZZO_KG DECIMAL(5,2),
    DATA_SEMINA DATE,
    DATA_RACCOLTO DATE,
	ID_PARTICELLA BIGINT,
	ID_ORTAGGIO BIGINT,
	FOREIGN KEY (ID_PARTICELLA) REFERENCES DATI_PARTICELLA(ID_PARTICELLA),
	FOREIGN KEY (ID_ORTAGGIO) REFERENCES DATI_ORTAGGIO(ID_ORTAGGIO)
);

-- Tabella dati ambiente
CREATE TABLE DATI_AMBIENTE (
    ID_AMBIENTE BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TEMPERATURA_MEDIA DECIMAL(5,2),
    UMIDITA_MEDIA DECIMAL(5,2),
    PRECIPITAZIONI DECIMAL(6,2),
    IRRAGGIAMENTO_MEDIO DECIMAL(5,2),
    OMBREGGIAMENTO_MEDIO DECIMAL(5,2),
    DATA_RILEVAZIONE DATE
);

-- Tabella dati rilevazione terreno
CREATE TABLE DATI_RILEVAZIONE_TERRENO (
    ID_RILEVAZIONE_TERRENO BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PH_SUOLO DECIMAL(3,1),
    UMIDITA DECIMAL(5,2),
    CAPACITA_ASSORBENTE DECIMAL(5,2),
    POROSITA DECIMAL(5,2),
    TEMPERATURA DECIMAL(5,2),
    DATA_RILEVAZIONE DATE,
	ID_PARTICELLA BIGINT,
	FOREIGN KEY (ID_PARTICELLA) REFERENCES DATI_PARTICELLA(ID_PARTICELLA)
);

-- Tabella dati produzione
CREATE TABLE DATI_PRODUZIONE (
    ID_PRODUZIONE BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    QUANTITA_RACCOLTO DECIMAL(10,2),
    QUANTITA_RACCOLTO_VENDUTO DECIMAL(10,2),
	QUANTITA_RACCOLTO_MARCIO DECIMAL(10,2),
	QUANTITA_RACCOLTO_TERZI DECIMAL(10,2),
    FATTURATO_RACCOLTO DECIMAL(10,2),
    NUM_LAVORATORI INT,
    SPESE_PRODUZIONE DECIMAL(10,2),
    ID_COLTURA BIGINT,
    FOREIGN KEY (ID_COLTURA) REFERENCES DATI_COLTURA(ID_COLTURA)
);

CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
   	JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION  
(
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
    references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
    references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;